---
all:
  children:
    cisco_access_switches:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_network_cli_ssh_type: paramiko
        ansible_user: "{{ vault_ansible_user }}"
        ansible_password: "{{ vault_ansible_password }}"
        ansible_become: true
        ansible_become_method: enable
        ansible_become_password: "{{ vault_ansible_become_password }}"
        ansible_paramiko_look_for_keys: false
        ansible_paramiko_allow_agent: false
        ansible_ssh_common_args: >-
          -oKexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
          -oHostKeyAlgorithms=+ssh-rsa
          -oPubkeyAcceptedAlgorithms=+ssh-rsa
          -oPubkeyAuthentication=no
          -oPreferredAuthentications=password
          -oPasswordAuthentication=yes
          -oStrictHostKeyChecking=no

      hosts:
        access-sw-01:
          ansible_host: 172.16.7.2
