---
all:
  children:
    cisco_access_switches:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_network_cli_ssh_type: paramiko
        ansible_user: "{{ vault_ansible_user }}"
        ansible_password: "{{ vault_ansible_password }}"
        ansible_become: true
        ansible_become_method: enable
        ansible_become_password: "{{ vault_ansible_become_password }}"
        ansible_paramiko_look_for_keys: false
        ansible_paramiko_allow_agent: false
        ansible_ssh_common_args: >-
          -oKexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
          -oHostKeyAlgorithms=+ssh-rsa
          -oPubkeyAcceptedAlgorithms=+ssh-rsa
          -oPubkeyAuthentication=no
          -oPreferredAuthentications=password
          -oPasswordAuthentication=yes
          -oStrictHostKeyChecking=no

      hosts:
        Alotau-Sw1:
          ansible_host: 172.16.21.2
        Cameron-Rd-SW1:
          ansible_host: 172.16.17.2
        Cameron-Rd-SW2:
          ansible_host: 172.16.17.3
        Goroka-Sw1:
          ansible_host: 172.16.5.2
        Hagen-SW1:
          ansible_host: 172.16.15.2
        HarbourCity-FSW02:
          ansible_host: 172.16.2.3
        HarbourCity-FSW04:
          ansible_host: 172.16.2.5
        HarbourCity-SW1:
          ansible_host: 172.16.2.2
        HarbourCity-SW3:
          ansible_host: 172.16.2.4
        Hides-SW1:
          ansible_host: 172.16.6.2
        Jackson-Airport-FSW:
          ansible_host: 172.16.7.2
        KBCGF_FSWX1:
          ansible_host: 10.10.255.40
        KBC-GF-FSW-new:
          ansible_host: 10.10.18.10
        Kimbe-FSW:
          ansible_host: 172.16.8.2
        Kokopo-FSW:
          ansible_host: 172.16.9.2
        Kokopo-SW1:
          ansible_host: 10.1.12.2
        LaeMainMarket-FSW:
          ansible_host: 172.16.3.2
        LaeMktbr-Lvl1-FSW:
          ansible_host: 172.16.3.3
        Lae-TT-SW1:
          ansible_host: 172.16.11.2
        Lihir-Sw1:
          ansible_host: 172.16.13.2
        Madang-SW1:
          ansible_host: 172.16.14.2
        POM-Branch-FSW2:
          ansible_host: 172.16.20.3
        Pom-SW1:
          ansible_host: 172.16.20.2
        Vision-City-SW1:
          ansible_host: 172.16.16.2
        WAI-DC-FSW01:
          ansible_host: 10.10.255.60
        WAI-DC-FSW05:
          ansible_host: 10.10.255.64
        WAI-DC-FSW06:
          ansible_host: 10.10.255.65
        WAI-DC-FSW07:
          ansible_host: 10.10.255.66
        WAI-DC-FSW08:
          ansible_host: 10.10.255.67
        Wewak-SW1:
          ansible_host: 172.16.18.2
        KBCGF_FSWX_2:
          ansible_host: 10.10.255.41
        KBC-GF-FSW1:
          ansible_host: 10.10.18.4
        KBHBC_WAN_SW:
          ansible_host: 10.10.22.254
        KBC-GF-FSW3:
          ansible_host: 10.10.18.6
        KBC-WAN-2960:
          ansible_host: 10.10.18.254
        KBHLv9_WAN_SX:
          ansible_host: 10.10.21.3
        KBHLv9_FSW1:
          ansible_host: 10.10.21.4
        KBHLv9_FSW2:
          ansible_host: 10.10.21.5
